<div class="pageContextNavigation span-5">
  <nav>
    <h4><a href="../index.stm">eLearning Tools Home</a></h4>
    <h4><a href="../digitalmedia/index.stm">Digital Media</a></h4>
    <h4><a href="index.stm">Video Streaming</a></h4>
    <ul class="sf-menu">
      <li><a href="faqs.stm">Frequently Asked Questions</a></li>
      <li><a href="http://www.csus.edu/atcs/tools/plugins.stm#video-players" target="_blank">Get Video Players</a></li>
      <li><a href="problem_form.stm">Problem Form</a></li>
      <li><a href="videostreaming_faculty.stm">Faculty Support</a></li>
      <li><a href="videostreaming_students.stm">Student Support</a></li>
    </ul>
    <h4><a href="#">Related</a></h4>
    <ul class="sf-menu">
      <li><a href="http://www.csus.edu/atcs/tools/mediaserver/index.stm" target="_blank">Faculty Media Server</a></li>
      <li><a href="http://www.apple.com/support/quicktime" target="_blank">Desktop Help</a></li>
      <li><a href="http://www.apple.com/support/quicktime" target="_blank">Apple iOS Help</a></li>
      <li><a href="http://www.apple.com/support/quicktime" target="_blank">Android Help</a></li>
      <li><a href="http://www.csus.edu/irt/STC/" target="_blank">Student Technology Center</a></li>
    </ul>
    <h4><a href="#">Help</a></h4>
    <ul class="sf-menu">
      <li><a href="#">Faculty and Staff</a>
        <ul>
          <li><a href="mailto:vs-courses@csus.edu">Email ATCS Support</a></li>
          <li><a href="http://www.csus.edu/sacct/support.stm" target="_blank">Ask a Consultant</a></li>
          <li><a href="../contact-us.stm">Contact Us</a></li>
        </ul>
      </li>
      <li><a href="#">Students</a>
        <ul>
          <li><a href="mailto:servicedesk@csus.edu">Email Service Desk</a></li>
          <li><a href="mailto:stc@csus.edu">Email Student Technology Center</a></li>
          <li><a href="../contact-us.stm">Contact Us</a></li>
        </ul>
      </li>
    </ul>
  </nav>
</div>