<div class="span-24 last">
	<div class="span-17 .ss-videoplayer-container" id="osmfcontainer">
		<?php echo $this->partial('index/_osmfplayer.phtml'); ?>
	</div>
    
    <div class="span-7 last ss-coursevideos-list" id="course_video_container">
    	<h3>Course Videos</h3>
    	<ul>
  			<?php echo $this->partialLoop('index/_courseVideoLoop.phtml', $this->coursevideos);?>
       </ul>
	</div>
</div>

<div class="span-24 last">
	
	<div class="span-5 pagenav-container">
		<?php echo $this->partial('index/_nav.phtml'); ?>	
	</div>


	<div class="ss-videogallery span-19 last" id="videogallery">
		<header>
	    	<h3>Courses</h3>
	  	</header>
	  
		<div class="ss-videogallery-list">
	   		<ul>
	  			<?php echo $this->partialLoop('index/_courseLoop.phtml', $this->courses);?>
	    	</ul>
		</div>   
	</div>

</div>      